#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.vps"
ENV_EXAMPLE="$ROOT_DIR/.env.vps.example"
COMPOSE_FILE="$ROOT_DIR/docker-compose.vps.yml"
BOOTSTRAP_SCRIPT="$ROOT_DIR/scripts/vps/bootstrap-all.sh"

DOMAIN=""
SKIP_TOOLS=false
NON_INTERACTIVE=false
WITH_UFW=false

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/vps/deploy-e2e.sh --domain app.example.com [options]

Options:
  --domain <value>       Domain or subdomain for deployment (required)
  --skip-tools           Skip installing Node/Python/Docker tools
  --with-ufw             Configure UFW to allow ports 22, 80, 443
  --non-interactive      Fail instead of prompting for confirmation
  -h, --help             Show help
USAGE
}

log() {
  printf "\n[%s] %s\n" "$(date +'%H:%M:%S')" "$1"
}

die() {
  echo "ERROR: $1" >&2
  exit 1
}

confirm() {
  local message="$1"
  if [ "$NON_INTERACTIVE" = true ]; then
    die "$message (non-interactive mode enabled)"
  fi

  read -r -p "$message Continue? [y/N]: " answer
  case "$answer" in
    y|Y|yes|YES) ;;
    *) die "Aborted by user." ;;
  esac
}

valid_domain() {
  local value="$1"
  [[ "$value" =~ ^[A-Za-z0-9.-]+$ ]] && [[ "$value" == *.* ]]
}

docker_compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
    return
  fi

  if sudo docker compose version >/dev/null 2>&1; then
    sudo docker compose "$@"
    return
  fi

  die "Docker Compose plugin is not available."
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --domain)
      [ "$#" -ge 2 ] || die "Missing value for --domain"
      DOMAIN="$2"
      shift 2
      ;;
    --skip-tools)
      SKIP_TOOLS=true
      shift
      ;;
    --non-interactive)
      NON_INTERACTIVE=true
      shift
      ;;
    --with-ufw)
      WITH_UFW=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[ -f "$COMPOSE_FILE" ] || die "Compose file not found: $COMPOSE_FILE"

if [ -z "$DOMAIN" ]; then
  die "Please pass --domain, for example --domain app.example.com"
fi

if ! valid_domain "$DOMAIN"; then
  die "Invalid domain format: $DOMAIN"
fi

if ! command -v apt-get >/dev/null 2>&1; then
  die "This script supports Ubuntu/Debian systems (apt-get) only."
fi

if [ "$SKIP_TOOLS" = false ]; then
  [ -x "$BOOTSTRAP_SCRIPT" ] || chmod +x "$BOOTSTRAP_SCRIPT"
  log "Installing Node, Python, and Docker toolchain"
  "$BOOTSTRAP_SCRIPT"
else
  log "Skipping tool installation (--skip-tools enabled)"
fi

log "Checking Docker engine availability"
if ! docker info >/dev/null 2>&1 && ! sudo docker info >/dev/null 2>&1; then
  die "Docker is not available after setup."
fi

if [ "$WITH_UFW" = true ]; then
  log "Configuring UFW firewall (22, 80, 443)"
  if command -v ufw >/dev/null 2>&1; then
    sudo ufw allow 22/tcp
    sudo ufw allow 80/tcp
    sudo ufw allow 443/tcp
    sudo ufw --force enable
  else
    echo "UFW not installed; skipping firewall setup."
  fi
fi

log "Writing deployment environment file"
if [ ! -f "$ENV_EXAMPLE" ]; then
  die "Missing environment template: $ENV_EXAMPLE"
fi
cp "$ENV_EXAMPLE" "$ENV_FILE"
{
  echo "# Generated by deploy-e2e.sh"
  echo "DOMAIN=$DOMAIN"
} > "$ENV_FILE"

PUBLIC_IP="$(curl -4 -fsS https://api.ipify.org || true)"
RESOLVED_IPS="$(getent ahostsv4 "$DOMAIN" 2>/dev/null | awk '{print $1}' | sort -u | tr '\n' ' ')"

if [ -n "$PUBLIC_IP" ] && [ -n "$RESOLVED_IPS" ]; then
  if ! echo "$RESOLVED_IPS" | grep -qw "$PUBLIC_IP"; then
    confirm "DNS for $DOMAIN does not currently resolve to this VPS IP ($PUBLIC_IP)."
  fi
else
  echo "Warning: Could not fully verify DNS resolution for $DOMAIN."
fi

log "Building and starting containers"
docker_compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build

log "Waiting for service health checks"
HEALTH_OK=false
for _ in $(seq 1 40); do
  if curl -kfsS "https://$DOMAIN/api/health" >/dev/null 2>&1; then
    HEALTH_OK=true
    break
  fi
  sleep 3
done

if [ "$HEALTH_OK" != true ]; then
  echo "Warning: HTTPS health check did not pass yet."
  echo "Run logs with: ./scripts/vps/logs.sh"
else
  echo "Health check passed at https://$DOMAIN/api/health"
fi

log "Deployment status"
docker_compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps

echo
echo "Done."
echo "Open your app at: https://$DOMAIN"
echo "API health endpoint: https://$DOMAIN/api/health"
